swagger: "4.0"
info:
  title: "OZmap API"
  description: >
    API construída para teste técnico do dev Antonio Neto para a empresa OZmap
  version: "1.0.0"
  contact:
    email: abdpneto@gmail.com
host: "localhost:3000"
paths:
  /:
    get:
      summary: "Verifica se o servidor está conectado"
      description: "Caso a API esteja online, gera uma mensagem indicando o host e a porta utilizados"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "O servidor está conectado"
          schema:
            $ref: "#/definitions/Health"
        500:
          $ref: "#/responses/500"

responses:
  500:
    description: Internal Server Error
    schema:
      $ref: "#/definitions/Error"
definitions:
  Health:
    type: "string"
    properties:
      status:
        type: "string"
        enum:
          - "Seu servidor esta rodando em http://localhost:3000"
#   /users:
#     get:
#       summary: "Listagem de um ou todos os usuários"
#       description: "Lista todos os usuários cadastrados na API"
#       consumes:
#         - "application/json"
#       produces:
#         - "application/json"
#       responses:
#         200:
#           description: "Service is up and healthy"
#           schema:
#             $ref: "#/definitions/Health"
#         500:
#           $ref: "#/responses/500"

# responses:
#   500:
#     description: Internal Server Error
#     schema:
#       $ref: "#/definitions/Error"

# paths:
#   /:
#     get:
#       summary: "Check the status of the service"
#       description: "If the service is up and running correctly the response will be 'UP'"
#       consumes:
#         - "application/json"
#       produces:
#         - "application/json"
#       responses:
#         200:
#           description: "Service is up and healthy"
#           schema:
#             $ref: "#/definitions/Health"
#         500:
#           $ref: "#/responses/500"

# responses:
#   500:
#     description: Internal Server Error
#     schema:
#       $ref: "#/definitions/Error"

# definitions:
#   Health:
#     type: "object"
#     properties:
#       status:
#         type: "string"
#         enum:
#           - "UP"
#           - "DOWN"
